services:
  webapp:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - database
    volumes:
      - .:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    env_file:
      - .docker/env/docker.env
    depends_on:
      mysql:
        condition: service_healthy
      mailer:
        condition: service_started

  mysql:
    image: mysql:8.0.35
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33306:3306"
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_DATABASE: master_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp_user", "-papp_password" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - database
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql

  mailer:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - database

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_ALLOW_ANONYMOUS: '1'
      MERCURE_CORS_ALLOWED_ORIGINS: '*'
    ports:
      - "1337:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - database

volumes:
  mysql_data:
  mercure_data:
  mercure_config:

networks:
  database:
    driver: bridge
